# Generated by Django 4.2 on 2023-04-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdwords',
            name='trl_word',
            field=models.TextField(default='ЯБЛОКО'),
        ),
        migrations.AlterField(
            model_name='bdwords',
            name='word',
            field=models.TextField(default='APPLE'),
        ),
    ]
